# Change these first
owner: ku1on       # Твой GitHub username или организация
repo: bullminer-status           # Имя репозитория (например, status)

sites:
  - name: Главная страница
    url: https://bullminer.ru/
  - name: Каталог товаров
    url: https://bullminer.ru/asicminers
  - name: API (криптовалюты)
    url: https://bullminer.ru/api/crypto-rates
  - name: Файл robots.txt
    url: https://bullminer.ru/robots.txt

status-website:
  cname: status.bullminer.ru
  logoUrl: https://bullminer.ru/logo.svg
  name: Bullminer Status
  introTitle: "📊 Статус сервисов Bullminer"
  introMessage: |
    Это публичная статус-страница **Bullminer**.  
    Здесь можно отслеживать доступность сайта, API и административных сервисов в реальном времени.  
    Все данные берутся автоматически из [этого репозитория](https://github.com/ku1on/bullminer-status).

  navbar:
    - title: Статус
      href: /
    - title: Главный сайт
      href: https://bullminer.ru
    - title: GitHub
      href: https://github.com/ku1on/bullminer-status
